services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    env_file:
      - .env
  
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - backend
    volumes:
      # Files individually assigned a volume due to MacOS compatibility
      # on building tailwind on ARM architectures
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
