services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - PORT=8000
      - UV_LINK_MODE=copy
  
  # frontend:
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     - PORT=3000
  #   depends_on:
  #     - backend
  
  # db:
  #   image: postgres:15
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=bettertldr
  #     - POSTGRES_PASSWORD=bettertldr
  #     - POSTGRES_DB=bettertldr